version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    
  app:
    build:
      context: ./build_scripts/worker_process
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./modules:/app
    command: python3 modules/worker_process.py

#   zookeeper:
#     image: 'bitnami/zookeeper:3'
#     ports:
#       - '2181:2181'
#     volumes:
#       - 'zookeeper_data:/bitnami'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: 'bitnami/kafka:2'
#     ports:
#       - '9092:9092'
#     volumes:
#       - 'kafka_data:/bitnami'
#     environment:
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#     depends_on:
#       - zookeeper

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local